apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-api
  name: ks-api-service
spec:
  ports:
  - name: http
    port: 80
    nodePort: 32607
    targetPort: 80
  selector:
    app: ks-api-pod
  type: NodePort